---
# handlers file for setup-apache
 - name: start the service
   service:
     name: httpd
     state: started
   when: ansible_os_family == "RedHat"

 - name: start service
   service:
     name: apache2
     state: started
   when: ansible_os_family == "Debian"

 - name: restart the service
   service:
     name: httpd
     state: restarted
   when: ansible_os_family == "RedHat"

 - name: restart service
   service:
     name: apache2
     state: restarted
   when: ansible_os_family == "Debian"

