---
- name: This playbook is for creating a file
  hosts: all
 # become: true
  gather_facts: no
  tasks:
  - name: creating a directory
    file:
      path: /home/ansadmin/dir1
      state: directory
