---
- name: This playbook installs http on web servers
  hosts: webservers
  become: true
  tasks: 
  - name: install packages httpd
    yum:  
      name: httpd
      state: installed
    notify: start the service

  handlers:    
  - name: start the service
    service:
      name: httpd
      state: started    
